# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-test
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: csi-driver-nfs
      namespace: storage
  values:
    image:
      repository: nginx
      tag: 1.19.6
    replicaCount: 1
    service:
      app:
        controller: echo
        ports:
          http:
            port: *port
    persistence:
      storageClass: "nfs-direct"
      size: 100Mi
      mountPath: /usr/share/nginx/html
    securityContext:
      runAsNonRoot: true
      runAsUser: 101 # NGINX typically runs as user 101
      runAsGroup: 101
      seccompProfile:
        type: RuntimeDefault
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 128Mi
    probes:
      liveness: &probes
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
      readiness: *probes
    ingress:
      app:
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /
        hosts:
          - host: "{{ .Release.Name }}.local.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
