# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:XBg2sIMkEmxVfGd5Z/Qd9qlRhg40jXKDGQEBl+OkgOumA6+VGm2gEBiP8olFXjUofjd0xN4pKhG/abJyEOebkcpD4eNApKR+dmYrz297priXusP8roHPi6XvspRV5h1P3etZMIoWcNB1EBIqlzb7IycdADWm5uhrlPMxh1mCDOYibi7hkHsnIoecwABqNvHY5nAkrMEe99Sf/q1RsP62+nLwfDGVEwlB0YHX7JqlW/gEm0Ux4g==,iv:S+9xBXwoXm548tHMc/I3TzuG/YlSZlPYMt0nGLd1c18=,tag:lPa7/CI1DvudY7z33Ptw+Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ekacrgurve3jl2z028kfy684q7vudmkzufazzfhspzfufncs6g8sqfg8q9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVURMTHdlSHpGQ1c0dDdx
        WkVVaU1mUkkzZHd4UlB3NE96RnBFWUhobFRZCmdzZXNVZkZ4TTduWlpSRzBraHJF
        RTR2NnlBMzRISnlqMTVocHFZeTBsMnMKLS0tIGUxb2diVDg5QTI3UVN4STVRMy8w
        WnBSTllxdkZhUm5ZbUNkQXpwZ3hQYjAKIh8L0RBRwudpY9NmocF8NDBfMU6meDJv
        risUVyLrZRqJ9nsLcUoSSszuMSn9Qmzo85XiK8JIL7wuYu+TUnrUfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-17T19:45:25Z"
  mac: ENC[AES256_GCM,data:ZFd4OpUZ+qZdhQ382e84LDyFwURWCRtdGXqgLX6fMpuiotxnBMpEyoUU0DTgtFkYEVsb5+4XqGrsx8PO7DMcllE48IEQ4fIpatvLYqyBas3RuleyweQgu0BDfhBjvcQBsSYfyO5J4+76v5zxAhjbwRorlz2QHy2ltMf8XPwzasA=,iv:gm3nN84eb8ZmtgvdAay/KVM+mLT8l2lvxiExYn7c0dI=,tag:ryjfDKocL9Gih4j0k/K1ug==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
