---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1ekacrgurve3jl2z028kfy684q7vudmkzufazzfhspzfufncs6g8sqfg8q9"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1ekacrgurve3jl2z028kfy684q7vudmkzufazzfhspzfufncs6g8sqfg8q9"
stores:
  yaml:
    indent: 2
