apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-web
  namespace: default
specs:
  replicas: 1
  selector:
    matchLabels:
      app: local-web
  template:
    metadata:
      labels:
        app: local-web
    spec:
      containers:
        - name: local-web
          image: nginx:1.19.6
          ports:
            - containerPort: 80
          volumeMounts:
            - name: local
              mountPath: /usr/share/nginx/html
      volumes:
        - name: local
          hostPath:
            path: /var/www/html
