---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-direct
provisioner: nfs.csi.k8s.io
parameters:
  - name: server
    valueFrom:
      secretKeyRef:
        name: nfs-secret
        key: server
  - name: share
    valueFrom:
      secretKeyRef:
        name: nfs-secret
        key: share
reclaimPolicy: Delete
volumeBindingMode: Immediate
# Note: The first two options are strictly for NFSv4.2
mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime"]
