apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:0P+7rQ6U78ynLkvMHfsZ29BAHyBn,iv:rfykXOExTSaicbxJUgjC6UvShUluhQLTmwVT5NzaIUo=,tag:rIo+T+MBAE3Vuxye50KKow==,type:str]
  SECRET_NFS_SERVER: ENC[AES256_GCM,data:Y72v0o6EfvaneTZN,iv:IvEqQqRPiJN9hYC7r5Oo8VmdJZPS/m50JXj3U2dEq2k=,tag:D37bRw2sK/ewmoB1/elDgQ==,type:str]
  SECRET_NFS_PATH: ENC[AES256_GCM,data:g87jCknDABxssXM=,iv:Frx5b84FHgwZ9kNjA0vmD8qTpUMCBqXvJny3ehUkC3M=,tag:0tQn+Z2Xe1UnpFpEBSautQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ekacrgurve3jl2z028kfy684q7vudmkzufazzfhspzfufncs6g8sqfg8q9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SlM1eFFmOGl3OGtXRElB
        MnVnSGNWNkJ4amxFUDhxNHN3NzRMa05yM2hzCmVqT1RxR0xYYWwvaVZreEV1QUFn
        eEp1QlJmRENhUnJ1cGlpT0RaSXRaeHMKLS0tIEJxVnpKRVJlQW9NWm9uZGhVMENU
        NXZkbkhPSUZGa3RwQXBVdk5yTzNCbFkK427DzTcJbMRcQDKdM6crRfEfl3j2O0d7
        m3JzAD5qFZ3FKrrrkQNIuSQfTl6fvw8zpk3RoMeP06MLOIJmH7lTkw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-23T22:07:46Z"
  mac: ENC[AES256_GCM,data:ij+M7ZYUW9edx8eH/Fr5bGl3wjVT6ot1jHNTcLHgMQ3CV2H8plpDQ7O3K4PTH11wHG4ChVClz0eEMO3bORLtXhm0sA3Q0x9siow2BESySIAC1DU60N5BCQH1ro+pCPUKLd5MEv1ZXWoM1DTvxG0h4EdPzp3d16rZaWOn9lci2dc=,iv:02cMraUlp8nFV/h97nQi8eHM3veZ/gB760zxlISbQDI=,tag:wGRVVJSx9CWcXx/DDbYPxA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
