apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:0ZA72J8mVX8qC3lWv6xvZHBsyVTE,iv:+Lq/xxpJhczbhM8EYCebOtlfySrLLA8L8aGWVTJDCf0=,tag:b3Oi1NiixrGxosm6f4Bu2g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ekacrgurve3jl2z028kfy684q7vudmkzufazzfhspzfufncs6g8sqfg8q9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aUlKRVhqNkk1Q0VoQnZi
        c0dNMVRONXozNTFDNDdUcE9PMGVXNHRVbnh3Ck5JR011dHh4NjQ2b2JjWXFCbXJH
        Z1lSekNOVGZtUHByRW9mOTFwVTZlRFEKLS0tIGlQZVpxRjd6aWwzOHdOakFpNHdQ
        Y0xKM3dET0QvOS9HZ3BDUkIyY0hIVUkKNr+54Si5MEBgzxslKiXrWW6t5eV/n8Ul
        NGSxyDJ+hMfaPuqKCDM0Ov4KoJHom3qVV887xxOHPI10op4gVDyiIw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-17T19:45:25Z"
  mac: ENC[AES256_GCM,data:5UBuEkAe7wfSt9RPjGb2St3pYoU8QMNp8myL742BEcWczPzCWFXH7p2/bAxFfEBBhJGJo6sjAWO6b1rOXQwj3jGWfD2XWFRGQZ4oOQ7PMABeLMp9kUoNeRIiKjAsz2Htye1r93YPp+eEIUfC/cXmdY67mla6VY01EapD+d1ibrA=,iv:GPd9TD1PI8CuiXgJhAgsfLpM8Z/k9T2g0z3XOp7PsHQ=,tag:31AM5HSHg7CIXUT0BLH/mg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
