# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:bLsGEKdIMnKyAzD3SoG95mGGhGHO0i1WVPquE3hDXy36dWGRoq6AiQ==,iv:8djok7iSqsI3OeYv5poSLBWgMgpLtqw3UFyTkAeUNQ4=,tag:zZn+cb8Sh9OYer3sWSisfQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ekacrgurve3jl2z028kfy684q7vudmkzufazzfhspzfufncs6g8sqfg8q9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bXQwczdjSTdEUTZUc0pm
        OFM4TlJSOHBIN240VnhVblc1Zkx4M1FnR1ZzCkdxV29ESElQa1ZFUTZwTmk3M2Iz
        YVNvTWNWQVRuQ3F0d2l4QWVzUXBNa2sKLS0tIFA2d29ZTEpsaEl3Zy9ya2tBUW96
        dmRsNENVMVgyRHYwNjJMRm54RnVSMlEKymbvSuSbeiHteA6C7qHlliTDB+sXUk3h
        J77/CH+yi5e0oxnEqbTAMiRFnlmA7YGGILliAUxTX0z9Ajor6mwqIg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-17T19:45:25Z"
  mac: ENC[AES256_GCM,data:87Em7NS+MTpvC26V/mMB4gWfaF+m1uZ9WrNjiOY663RnlMnMrDB8FDmbcymcdamHuErXdLOlIOyNqfsPUqeWpMlyfcUQ2+AstYb417RavryICxYX+TiCi0SpODWu4lOgcL8QA5OoHG0D1WG0y7R4FWPczjvrFRHjzZb+pUg9oB4=,iv:enVoyxn0Gulj4OBDDkPbCDjaDDXDeENydths7TqgjtQ=,tag:Ih1ElrLSKg0xWpYvnnQ9IA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
