---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
components:
  - ../../components/alerts
  - ../../components/common
resources:
  - namespace.yaml
  - ./csi-driver-nfs/ks.yaml
